# ========== ECS Service ==========

resource "aws_ecs_service" "this" {
  name                              = var.ecs_service_name
  cluster                           = var.ecs_cluster_id
  task_definition                   = var.ecs_task_definition_arn
  desired_count                     = var.ecs_service_desired_count
  health_check_grace_period_seconds = var.ecs_health_check_grace_period_seconds
  launch_type                       = var.ecs_service_launch_type

  network_configuration {
    security_groups = var.ecs_service_security_groups_id
    subnets         = var.ecs_service_subnets_id
  }

  load_balancer {
    target_group_arn = var.target_group_arn
    container_name   = var.container_name
    container_port   = var.container_port
  }

  deployment_controller {
    type = var.ecs_service_deployment_controller_type
  }

  lifecycle {
    // Avoid changes generated by autoscaling or new CodeDeploy changes
    ignore_changes = [
      desired_count,
      task_definition,
      load_balancer,
    ]
  }

  tags = merge(local.default_tags, var.tags)
}
